development:
    adapter: postgresql
    encoding: unicode
    database: my_test_app_development
    pool: 5
    username: taspai
    password: toto
    host: localhost
    port: 3000

test:
    adapter: postgresql
    encoding: unicode
    database: my_test_app_test
    pool: 5
    username: taspai
    password: toto
    host: localhost
    port: 3000
